### ISSUE TITLE
MeSH versions newer than 2015 throw "index out of range"

### ISSUE THREAD

**Issue by michelole** [Shugyousha/mesh2solrsyn#1]
Hi!

Thanks for sharing your code!

I tried to run your program with different versions of MeSH and I was only able to get some valid output with the 2015 version:

`go run mesh2solrsyn.go d2015.bin < mtrees2015.bin > synonyms.txt`

When I run with newer versions, I get the following:

```
panic: runtime error: index out of range

goroutine 19 [running]:
github.com/Shugyousha/mesh.parseMeSH(0xc420223000, 0x1000, 0x1000, 0x1128140, 0xc42103c878, 0x71d, 0x1000, 0x0, 0x0, 0xa, ...)
	/Users/michel/go/src/github.com/Shugyousha/mesh/mesh.go:167 +0x7e6
created by github.com/Shugyousha/mesh.ParseToSliceAndMap
	/Users/michel/go/src/github.com/Shugyousha/mesh/mesh.go:195 +0xac
exit status 2
```

Am I missing something? Any plans to support newer versions?

Thank you in advance!

**Comment by Shugyousha** [comment]
Hi Michel

On Thu, Jul 27, 2017 at 10:39:20AM +0000, Michel Oleynik wrote:
> I tried to run your program with different versions of MeSH and I was
> only able to get some valid output with the 2015 version:
> 
> `go run mesh2solrsyn.go d2015.bin < mtrees2015.bin > synonyms.txt`
> 
> When I run with newer versions, I get the following:
> 
> ```
> panic: runtime error: index out of range
> 
> goroutine 19 [running]:
> github.com/Shugyousha/mesh.parseMeSH(0xc420223000, 0x1000, 0x1000, 0x1128140, 0xc42103c878, 0x71d, 0x1000, 0x0, 0x0, 0xa, ...)
> 	/Users/michel/go/src/github.com/Shugyousha/mesh/mesh.go:167 +0x7e6
> created by github.com/Shugyousha/mesh.ParseToSliceAndMap
> 	/Users/michel/go/src/github.com/Shugyousha/mesh/mesh.go:195 +0xac
> exit status 2
> ```
> 
> Am I missing something? Any plans to support newer versions?

This code could really use some love...

I had a look and it seems like the (very simple) MeSH parser chokes on
fields with multiline values like this for example:

MS = Deformity of the hip characterized by enlargement and deformation of the FEMUR HEAD and
FEMUR NECK, often with associated changes in the ACETABULUM. These changes may be
secondary to other diseases (e.g.  LEGG-PERTHES DISEASE; ARTHRITIS; HIP DISLOCATION,
CONGENITAL) or TRAUMA.

I will have a look if I can think of a clean way to deal with this case
without adding too much complexity. A quick hack would be to just ignore
those fields but I would prefer to clean up some stuff while I am fixing
this bug...

**Comment by Shugyousha** [comment]
Hi

I think I fixed the issue. Could you try again and let me know if the
changes worked for you?

I also tried to clean up the code a little. There is still much to do
but I don't have more time to invest at the moment.


Cheers,

Silvan

**Comment by michelole** [comment]
Seems to work now, thanks!

**Comment by Shugyousha** [comment]
On Sat, Jul 29, 2017 at 03:49:55PM +0000, Michel Oleynik wrote:
> Seems to work now, thanks!

Great! Thanks for the bug report
